repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        entry: ruff check --fix
        language: system
        types: [python]
      - id: ruff-imports
        name: Ruff import sorting
        entry: ruff check --select I --fix
        language: system
        types: [python]
      - id: ruff-format
        name: Ruff format
        entry: ruff format
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
